version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    - /react-app/node_modules
    - .:/react-app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /react-app/node_modules
      - .:/react-app
    command: ["npm", "run", "test"]